"use client";

import React, { useState, useRef, useEffect, useCallback } from 'react';
import {
    ChevronDown,
    ChevronRight,
    File,
    Folder,
    FolderOpen,
    Plus,
    Trash2,
    X,
    FolderPlus,
    FilePlus,
    MoreHorizontal,
    Copy,
    Download,
    Save,
} from 'lucide-react';
import { cn } from '@/lib/utils';

// --- Types ---

interface FSNode {
    id: string;
    name: string;
    type: 'file' | 'folder';
    content?: string;
    children?: FSNode[];
    language?: string;
}

interface OpenTab {
    id: string;
    name: string;
    modified?: boolean;
}

// --- Language Detection ---

const getLanguage = (filename: string): string => {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    const langMap: Record<string, string> = {
        py: 'python', ts: 'typescript', tsx: 'tsx', js: 'javascript',
        jsx: 'jsx', json: 'json', yaml: 'yaml', yml: 'yaml',
        md: 'markdown', css: 'css', html: 'html', sh: 'bash',
        env: 'env', toml: 'toml', cfg: 'config', txt: 'text',
        rs: 'rust', go: 'go', java: 'java', rb: 'ruby',
        sql: 'sql', graphql: 'graphql', proto: 'protobuf',
    };
    return langMap[ext] || 'text';
};

const getFileIcon = (filename: string): string => {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    const iconMap: Record<string, string> = {
        py: '🐍', ts: '🔷', tsx: '⚛️', js: '🟨', jsx: '⚛️',
        json: '📋', yaml: '⚙️', yml: '⚙️', md: '📝',
        css: '🎨', html: '🌐', sh: '💲', env: '🔒',
        toml: '⚙️', rs: '🦀', go: '🐹', java: '☕',
        sql: '🗃️', graphql: '◆', proto: '📦',
    };
    return iconMap[ext] || '📄';
};

// --- Default File System ---

const createDefaultFS = (code: string): FSNode[] => [
    {
        id: 'root-src',
        name: 'src',
        type: 'folder',
        children: [
            {
                id: 'src-main',
                name: 'main.py',
                type: 'file',
                content: code || '# Awaiting architecture lock...\n# No implementation generated yet.',
            },
            {
                id: 'src-agents',
                name: 'agents',
                type: 'folder',
                children: [
                    {
                        id: 'agents-init',
                        name: '__init__.py',
                        type: 'file',
                        content: '# Agent module initialization\nfrom .base import BaseAgent',
                    },
                    {
                        id: 'agents-base',
                        name: 'base.py',
                        type: 'file',
                        content: 'from abc import ABC, abstractmethod\n\nclass BaseAgent(ABC):\n    \"\"\"Base agent class for all agents.\"\"\"\n\n    @abstractmethod\n    def run(self, input: str) -> str:\n        pass\n\n    @abstractmethod\n    def get_tools(self) -> list:\n        return []',
                    },
                ],
            },
            {
                id: 'src-tools',
                name: 'tools',
                type: 'folder',
                children: [
                    {
                        id: 'tools-init',
                        name: '__init__.py',
                        type: 'file',
                        content: '# Tools module',
                    },
                ],
            },
            {
                id: 'src-config',
                name: 'config.yaml',
                type: 'file',
                content: 'agent:\n  name: "argus-agent"\n  version: "1.0.0"\n  runtime: "langgraph"\n\nsafety:\n  pii_filter: true\n  max_iterations: 25\n  injection_scan: true\n\nllm:\n  provider: "openai"\n  model: "gpt-4o-mini"\n  temperature: 0.3',
            },
        ],
    },
    {
        id: 'root-tests',
        name: 'tests',
        type: 'folder',
        children: [
            {
                id: 'tests-test',
                name: 'test_agent.py',
                type: 'file',
                content: 'import pytest\n\ndef test_agent_init():\n    \"\"\"Test agent initialization.\"\"\"\n    pass\n\ndef test_agent_run():\n    \"\"\"Test agent run method.\"\"\"\n    pass',
            },
        ],
    },
    {
        id: 'root-requirements',
        name: 'requirements.txt',
        type: 'file',
        content: 'langgraph>=0.1.0\nlangchain>=0.2.0\nopenai>=1.0.0\npinecone-client>=3.0.0\ncrewai>=0.1.0\npydantic>=2.0.0\npytest>=8.0.0',
    },
    {
        id: 'root-readme',
        name: 'README.md',
        type: 'file',
        content: '# Argus AI Agent\n\nGenerated by Argus Architect.\n\n## Quick Start\n\n```bash\npip install -r requirements.txt\npython src/main.py\n```\n\n## Architecture\n\nThis agent uses the **Supervisor Pattern** with CrewAI.\n',
    },
    {
        id: 'root-env',
        name: '.env.example',
        type: 'file',
        content: 'OPENAI_API_KEY=sk-...\nPINECONE_API_KEY=...\nPINECONE_ENV=us-east-1',
    },
];

// --- Syntax Highlighting (simple keyword-based) ---

const highlightCode = (code: string, language: string): React.ReactNode[] => {
    const lines = code.split('\n');

    const keywords: Record<string, string[]> = {
        python: ['import', 'from', 'class', 'def', 'return', 'if', 'else', 'elif', 'for', 'while', 'try', 'except', 'with', 'as', 'pass', 'raise', 'True', 'False', 'None', 'and', 'or', 'not', 'in', 'is', 'lambda', 'yield', 'async', 'await', 'self'],
        typescript: ['import', 'from', 'export', 'default', 'const', 'let', 'var', 'function', 'return', 'if', 'else', 'for', 'while', 'class', 'interface', 'type', 'extends', 'implements', 'new', 'this', 'async', 'await', 'try', 'catch', 'throw', 'true', 'false', 'null', 'undefined'],
        javascript: ['import', 'from', 'export', 'default', 'const', 'let', 'var', 'function', 'return', 'if', 'else', 'for', 'while', 'class', 'new', 'this', 'async', 'await', 'try', 'catch', 'throw', 'true', 'false', 'null', 'undefined'],
        yaml: [],
        json: [],
    };

    const langKeywords = keywords[language] || keywords['python'] || [];

    return lines.map((line, lineIdx) => {
        // Comment lines
        if (line.trimStart().startsWith('#') || line.trimStart().startsWith('//')) {
            return <span key={lineIdx} className="text-[#6A9955]">{line}</span>;
        }

        // String lines
        if (/^\s*(["'`]).*\1\s*$/.test(line)) {
            return <span key={lineIdx} className="text-[#CE9178]">{line}</span>;
        }

        // Tokenize
        const tokens = line.split(/(\b\w+\b|[^\w\s]|\s+)/g);
        return (
            <span key={lineIdx}>
                {tokens.map((token, i) => {
                    if (langKeywords.includes(token)) {
                        return <span key={i} className="text-[#C586C0]">{token}</span>;
                    }
                    if (/^(["'`]).*\1$/.test(token)) {
                        return <span key={i} className="text-[#CE9178]">{token}</span>;
                    }
                    if (/^\d+(\.\d+)?$/.test(token)) {
                        return <span key={i} className="text-[#B5CEA8]">{token}</span>;
                    }
                    if (/^[A-Z][A-Za-z]*$/.test(token)) {
                        return <span key={i} className="text-[#4EC9B0]">{token}</span>;
                    }
                    if (/^[@()\[\]{},;:=<>+\-*/!&|^~%.]$/.test(token)) {
                        return <span key={i} className="text-[#D4D4D4]">{token}</span>;
                    }
                    return <span key={i}>{token}</span>;
                })}
            </span>
        );
    });
};

// --- Inline Rename Input ---

const InlineInput = ({ defaultValue, onSubmit, onCancel, placeholder }: {
    defaultValue?: string;
    onSubmit: (value: string) => void;
    onCancel: () => void;
    placeholder?: string;
}) => {
    const [value, setValue] = useState(defaultValue || '');
    const ref = useRef<HTMLInputElement>(null);

    useEffect(() => {
        ref.current?.focus();
        ref.current?.select();
    }, []);

    return (
        <input
            ref={ref}
            value={value}
            placeholder={placeholder}
            onChange={(e) => setValue(e.target.value)}
            onKeyDown={(e) => {
                if (e.key === 'Enter' && value.trim()) onSubmit(value.trim());
                if (e.key === 'Escape') onCancel();
            }}
            onBlur={() => { if (value.trim()) onSubmit(value.trim()); else onCancel(); }}
            className="bg-[#1E1E2E] border border-primary/50 text-[11px] text-white px-1.5 py-0.5 rounded outline-none w-full font-sans"
        />
    );
};

// --- File Tree Item ---

const FileTreeItem = ({
    node,
    depth,
    activeFileId,
    onSelectFile,
    onDeleteNode,
    onCreateChild,
    expandedFolders,
    toggleFolder,
}: {
    node: FSNode;
    depth: number;
    activeFileId: string | null;
    onSelectFile: (id: string) => void;
    onDeleteNode: (id: string) => void;
    onCreateChild: (parentId: string, type: 'file' | 'folder') => void;
    expandedFolders: Set<string>;
    toggleFolder: (id: string) => void;
}) => {
    const isFolder = node.type === 'folder';
    const isExpanded = expandedFolders.has(node.id);
    const isActive = activeFileId === node.id;
    const [showActions, setShowActions] = useState(false);

    return (
        <div>
            <div
                className={cn(
                    "flex items-center gap-1 px-2 py-[3px] cursor-pointer text-[11px] group transition-colors select-none",
                    isActive ? "bg-primary/15 text-white" : "text-[#CCC] hover:bg-white/5"
                )}
                style={{ paddingLeft: `${depth * 12 + 8}px` }}
                onClick={() => {
                    if (isFolder) toggleFolder(node.id);
                    else onSelectFile(node.id);
                }}
                onMouseEnter={() => setShowActions(true)}
                onMouseLeave={() => setShowActions(false)}
            >
                {isFolder ? (
                    <>
                        {isExpanded ? <ChevronDown className="w-3 h-3 text-muted-foreground shrink-0" /> : <ChevronRight className="w-3 h-3 text-muted-foreground shrink-0" />}
                        {isExpanded ? <FolderOpen className="w-3.5 h-3.5 text-amber-400 shrink-0" /> : <Folder className="w-3.5 h-3.5 text-amber-400 shrink-0" />}
                    </>
                ) : (
                    <>
                        <span className="w-3 shrink-0" />
                        <span className="text-[10px] shrink-0">{getFileIcon(node.name)}</span>
                    </>
                )}
                <span className="truncate flex-1 ml-1">{node.name}</span>

                {showActions && (
                    <div className="flex items-center gap-0.5 shrink-0" onClick={(e) => e.stopPropagation()}>
                        {isFolder && (
                            <>
                                <button onClick={() => onCreateChild(node.id, 'file')} className="p-0.5 hover:bg-white/10 rounded" title="New File">
                                    <FilePlus className="w-3 h-3 text-muted-foreground hover:text-white" />
                                </button>
                                <button onClick={() => onCreateChild(node.id, 'folder')} className="p-0.5 hover:bg-white/10 rounded" title="New Folder">
                                    <FolderPlus className="w-3 h-3 text-muted-foreground hover:text-white" />
                                </button>
                            </>
                        )}
                        <button onClick={() => onDeleteNode(node.id)} className="p-0.5 hover:bg-destructive/20 rounded" title="Delete">
                            <Trash2 className="w-3 h-3 text-muted-foreground hover:text-destructive" />
                        </button>
                    </div>
                )}
            </div>

            {isFolder && isExpanded && node.children && (
                <div>
                    {node.children
                        .sort((a, b) => {
                            if (a.type === b.type) return a.name.localeCompare(b.name);
                            return a.type === 'folder' ? -1 : 1;
                        })
                        .map((child) => (
                            <FileTreeItem
                                key={child.id}
                                node={child}
                                depth={depth + 1}
                                activeFileId={activeFileId}
                                onSelectFile={onSelectFile}
                                onDeleteNode={onDeleteNode}
                                onCreateChild={onCreateChild}
                                expandedFolders={expandedFolders}
                                toggleFolder={toggleFolder}
                            />
                        ))}
                </div>
            )}
        </div>
    );
};

// --- Main VSCode Panel ---

interface VSCodePanelProps {
    code: string;
    isTyping: boolean;
}

export default function VSCodePanel({ code, isTyping }: VSCodePanelProps) {
    const [fileSystem, setFileSystem] = useState<FSNode[]>(() => createDefaultFS(code));
    const [activeFileId, setActiveFileId] = useState<string | null>('src-main');
    const [openTabs, setOpenTabs] = useState<OpenTab[]>([{ id: 'src-main', name: 'main.py' }]);
    const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set(['root-src', 'src-agents', 'src-tools']));
    const [creatingIn, setCreatingIn] = useState<{ parentId: string; type: 'file' | 'folder' } | null>(null);
    const editorRef = useRef<HTMLTextAreaElement>(null);

    // Sync code from parent (scenario step updates) into main.py
    useEffect(() => {
        if (code) {
            setFileSystem((prev) => updateNodeContent(prev, 'src-main', code));
        }
    }, [code]);

    // --- FS Helpers ---

    const findNode = useCallback((nodes: FSNode[], id: string): FSNode | null => {
        for (const n of nodes) {
            if (n.id === id) return n;
            if (n.children) {
                const found = findNode(n.children, id);
                if (found) return found;
            }
        }
        return null;
    }, []);

    const updateNodeContent = (nodes: FSNode[], id: string, content: string): FSNode[] => {
        return nodes.map(n => {
            if (n.id === id) return { ...n, content };
            if (n.children) return { ...n, children: updateNodeContent(n.children, id, content) };
            return n;
        });
    };

    const deleteNode = (nodes: FSNode[], id: string): FSNode[] => {
        return nodes
            .filter(n => n.id !== id)
            .map(n => n.children ? { ...n, children: deleteNode(n.children, id) } : n);
    };

    const addChild = (nodes: FSNode[], parentId: string, child: FSNode): FSNode[] => {
        return nodes.map(n => {
            if (n.id === parentId && n.type === 'folder') {
                return { ...n, children: [...(n.children || []), child] };
            }
            if (n.children) return { ...n, children: addChild(n.children, parentId, child) };
            return n;
        });
    };

    // --- Handlers ---

    const activeFile = activeFileId ? findNode(fileSystem, activeFileId) : null;

    const handleSelectFile = (id: string) => {
        const file = findNode(fileSystem, id);
        if (!file || file.type !== 'file') return;
        setActiveFileId(id);
        if (!openTabs.find(t => t.id === id)) {
            setOpenTabs(prev => [...prev, { id, name: file.name }]);
        }
    };

    const handleCloseTab = (id: string) => {
        setOpenTabs(prev => prev.filter(t => t.id !== id));
        if (activeFileId === id) {
            const remaining = openTabs.filter(t => t.id !== id);
            setActiveFileId(remaining.length > 0 ? remaining[remaining.length - 1].id : null);
        }
    };

    const handleDeleteNode = (id: string) => {
        setFileSystem(prev => deleteNode(prev, id));
        setOpenTabs(prev => prev.filter(t => t.id !== id));
        if (activeFileId === id) setActiveFileId(null);
    };

    const handleCreateChild = (parentId: string, type: 'file' | 'folder') => {
        setCreatingIn({ parentId, type });
        setExpandedFolders(prev => new Set([...prev, parentId]));
    };

    const handleCreateRootItem = (type: 'file' | 'folder') => {
        setCreatingIn({ parentId: '__root__', type });
    };

    const handleSubmitCreate = (name: string) => {
        if (!creatingIn) return;
        const newId = `${creatingIn.parentId}-${name.replace(/[^a-zA-Z0-9]/g, '')}-${Date.now()}`;
        const newNode: FSNode = {
            id: newId,
            name,
            type: creatingIn.type,
            ...(creatingIn.type === 'file' ? { content: '' } : { children: [] }),
        };

        if (creatingIn.parentId === '__root__') {
            setFileSystem(prev => [...prev, newNode]);
        } else {
            setFileSystem(prev => addChild(prev, creatingIn.parentId, newNode));
        }

        if (creatingIn.type === 'file') {
            setOpenTabs(prev => [...prev, { id: newId, name }]);
            setActiveFileId(newId);
        }

        setCreatingIn(null);
    };

    const handleCodeChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        if (!activeFileId) return;
        const newContent = e.target.value;
        setFileSystem(prev => updateNodeContent(prev, activeFileId, newContent));
        // Mark tab as modified
        setOpenTabs(prev => prev.map(t => t.id === activeFileId ? { ...t, modified: true } : t));
    };

    const toggleFolder = (id: string) => {
        setExpandedFolders(prev => {
            const next = new Set(prev);
            if (next.has(id)) next.delete(id);
            else next.add(id);
            return next;
        });
    };

    const fileContent = activeFile?.content || '';
    const fileLanguage = activeFile ? getLanguage(activeFile.name) : 'text';
    const lineCount = fileContent.split('\n').length;

    return (
        <div className="flex flex-col h-full bg-[#1E1E2E]">
            {/* VS Code Top Bar */}
            <div className="h-9 px-2 flex items-center justify-between border-b border-[#2D2D3D] bg-[#1E1E2E]">
                <div className="flex items-center gap-1">
                    <button onClick={() => handleCreateRootItem('file')} className="p-1 hover:bg-white/10 rounded transition-colors" title="New File">
                        <FilePlus className="w-3 h-3 text-muted-foreground hover:text-white" />
                    </button>
                    <button onClick={() => handleCreateRootItem('folder')} className="p-1 hover:bg-white/10 rounded transition-colors" title="New Folder">
                        <FolderPlus className="w-3 h-3 text-muted-foreground hover:text-white" />
                    </button>
                </div>
                <div className="flex items-center gap-1">
                    <button className="p-1 hover:bg-white/10 rounded transition-colors" title="Copy Code">
                        <Copy className="w-3 h-3 text-muted-foreground hover:text-white" />
                    </button>
                    <button className="p-1 hover:bg-white/10 rounded transition-colors" title="Download">
                        <Download className="w-3 h-3 text-muted-foreground hover:text-white" />
                    </button>
                </div>
            </div>

            {/* Main Content: File Tree + Editor */}
            <div className="flex-1 flex overflow-hidden">
                {/* File Tree Sidebar */}
                <div className="w-[140px] min-w-[140px] border-r border-[#2D2D3D] bg-[#181825] overflow-y-auto custom-scrollbar flex flex-col">
                    <div className="px-2 py-1.5 text-[9px] font-bold text-muted-foreground uppercase tracking-widest flex items-center justify-between border-b border-[#2D2D3D]">
                        <span>Explorer</span>
                    </div>
                    <div className="flex-1 py-1">
                        {fileSystem
                            .sort((a, b) => {
                                if (a.type === b.type) return a.name.localeCompare(b.name);
                                return a.type === 'folder' ? -1 : 1;
                            })
                            .map((node) => (
                                <FileTreeItem
                                    key={node.id}
                                    node={node}
                                    depth={0}
                                    activeFileId={activeFileId}
                                    onSelectFile={handleSelectFile}
                                    onDeleteNode={handleDeleteNode}
                                    onCreateChild={handleCreateChild}
                                    expandedFolders={expandedFolders}
                                    toggleFolder={toggleFolder}
                                />
                            ))}

                        {/* Inline creation at root level */}
                        {creatingIn?.parentId === '__root__' && (
                            <div className="px-2 py-0.5" style={{ paddingLeft: '8px' }}>
                                <InlineInput
                                    placeholder={creatingIn.type === 'file' ? 'filename.ext' : 'folder name'}
                                    onSubmit={handleSubmitCreate}
                                    onCancel={() => setCreatingIn(null)}
                                />
                            </div>
                        )}

                        {/* Inline creation inside folders (rendered after the expanded folder's children) */}
                        {creatingIn && creatingIn.parentId !== '__root__' && (
                            <div className="px-2 py-0.5" style={{ paddingLeft: '32px' }}>
                                <InlineInput
                                    placeholder={creatingIn.type === 'file' ? 'filename.ext' : 'folder name'}
                                    onSubmit={handleSubmitCreate}
                                    onCancel={() => setCreatingIn(null)}
                                />
                            </div>
                        )}
                    </div>
                </div>

                {/* Editor Area */}
                <div className="flex-1 flex flex-col overflow-hidden bg-[#1E1E2E]">
                    {/* Open Tabs */}
                    <div className="h-[30px] bg-[#181825] border-b border-[#2D2D3D] flex items-center overflow-x-auto custom-scrollbar">
                        {openTabs.map((tab) => (
                            <div
                                key={tab.id}
                                onClick={() => setActiveFileId(tab.id)}
                                className={cn(
                                    "flex items-center gap-1.5 px-3 h-full border-r border-[#2D2D3D] text-[11px] cursor-pointer select-none shrink-0 group transition-colors",
                                    activeFileId === tab.id
                                        ? "bg-[#1E1E2E] text-white border-t border-t-primary"
                                        : "bg-[#181825] text-[#888] hover:text-[#CCC]"
                                )}
                            >
                                <span className="text-[9px]">{getFileIcon(tab.name)}</span>
                                <span className="truncate max-w-[80px]">{tab.name}</span>
                                {tab.modified && <span className="w-1.5 h-1.5 bg-white/50 rounded-full shrink-0" />}
                                <button
                                    onClick={(e) => { e.stopPropagation(); handleCloseTab(tab.id); }}
                                    className="p-0.5 opacity-0 group-hover:opacity-100 hover:bg-white/10 rounded transition-all shrink-0"
                                >
                                    <X className="w-2.5 h-2.5" />
                                </button>
                            </div>
                        ))}
                    </div>

                    {/* Breadcrumb */}
                    {activeFile && (
                        <div className="h-[22px] px-3 flex items-center text-[10px] text-muted-foreground bg-[#1E1E2E] border-b border-[#2D2D3D] gap-1">
                            <span>{activeFile.name}</span>
                            <span className="text-[#555]">—</span>
                            <span className="uppercase text-[9px]">{fileLanguage}</span>
                            {isTyping && <span className="ml-auto text-primary animate-pulse text-[9px]">● Generating...</span>}
                        </div>
                    )}

                    {/* Code Editor */}
                    {activeFile ? (
                        <div className="flex-1 overflow-auto custom-scrollbar relative">
                            <div className="flex min-h-full">
                                {/* Line Numbers */}
                                <div className="sticky left-0 bg-[#1E1E2E] border-r border-[#2D2D3D] px-2 pt-2 text-right select-none z-10 shrink-0">
                                    {Array.from({ length: lineCount }, (_, i) => (
                                        <div key={i} className="text-[10px] leading-[18px] text-[#555] font-mono h-[18px]">
                                            {i + 1}
                                        </div>
                                    ))}
                                </div>

                                {/* Actual editable code area */}
                                <div className="flex-1 relative min-w-0">
                                    {/* Syntax highlighted overlay */}
                                    <pre className="absolute inset-0 p-2 font-mono text-[11px] leading-[18px] text-[#D4D4D4] pointer-events-none whitespace-pre overflow-visible">
                                        {highlightCode(fileContent, fileLanguage).map((line, i) => (
                                            <div key={i} className="h-[18px]">{line}</div>
                                        ))}
                                    </pre>

                                    {/* Textarea (invisible text, but handles input) */}
                                    <textarea
                                        ref={editorRef}
                                        value={fileContent}
                                        onChange={handleCodeChange}
                                        spellCheck={false}
                                        className="absolute inset-0 w-full h-full p-2 font-mono text-[11px] leading-[18px] bg-transparent text-transparent caret-white outline-none resize-none overflow-hidden"
                                        style={{ caretColor: '#D4D4D4' }}
                                    />
                                </div>
                            </div>
                        </div>
                    ) : (
                        <div className="flex-1 flex items-center justify-center text-muted-foreground/30 flex-col gap-2">
                            <File className="w-10 h-10" />
                            <p className="text-[11px] text-muted-foreground/50">Select a file to edit</p>
                        </div>
                    )}

                    {/* Status Bar */}
                    <div className="h-[22px] bg-[#181825] border-t border-[#2D2D3D] px-3 flex items-center justify-between text-[9px] text-muted-foreground shrink-0">
                        <div className="flex items-center gap-3">
                            {activeFile && (
                                <>
                                    <span>Ln {fileContent.split('\n').length}, Col 1</span>
                                    <span className="uppercase">{fileLanguage}</span>
                                </>
                            )}
                        </div>
                        <div className="flex items-center gap-3">
                            <span>UTF-8</span>
                            <span>Spaces: 2</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
